# Conclusions {#sec-conclusions}

The purpose of this template is to provide basic instructions in creating your
dissertation/thesis document. If you need assistance with writing, please visit
the Writing Center in the JKB or consult with your advisor. If you need
assistance with \LaTeX, there are tutorials and ample documentation online. You
may want to consult with your graduate-student peers who use \LaTeX. If you
discover something that would make this template more useful, please feel free
to make recommendations. There is also very good online documentation for Quarto.

Regardless of whether this template or some other method of formatting is
employed, you (the student) are responsible for following the guidelines found
in @sec-reqs. Below is a brief checklist of things to look for as you
review your thesis for formatting:

  - Check numbering of sections, figures, tables, equations to make sure they are consistent.	This is where you will be really glad that you are using \LaTeX.
  - Ensure that your table of contents, list of figures, and list of tables are up to date and that page numbers are correct. (Hurray for \LaTeX!)
  - Make sure all pages are numbered, beginning with the table of contents.
  - Be sure there is no extra white space at the bottom of any page except for the final page of a chapter.
  - Make sure there are no widows or orphans.^[A *widow* occurs when the last line of a paragraph ends up on the first line of a page. An *orphan* occurs when the first line of a paragraph appears on the last line of a page. Your document may require manual tweaking when it is in final form to get rid of widows and orphans.]

